### ISSUE TITLE
Add support for jruby 1.7.18

### ISSUE THREAD

**Issue by searls** [rspec-given/rspec-given#2]
The latest known working jruby version is 1.7.9.

When run under jruby 1.7.18, the tests fail with these myriad errors:

```
$ rake
Running specs
rspec spec
*********....................******...............................F..*******************...........********....****************************................*..*********.........*****************************************************......****************

Pending:
  Given::Assertions Assert { } with true assertion       Then { result != Failure() }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/assertions_spec.rb:15
  Given::Assertions Assert { } with false assertion       Then { result == Failure(Given::Assertions::AssertError, /Assert.*false/) }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/assertions_spec.rb:22
  Given::Assertions Assert { } when disabled       Then { result != Failure() }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/assertions_spec.rb:28
  Given::Assertions Precondition { } with true assertion       Then { result != Failure() }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/assertions_spec.rb:37
  Given::Assertions Precondition { } with false assertion       Then { result == Failure(Given::Assertions::PreconditionError, /Precondition.*false/) }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/assertions_spec.rb:44
  Given::Assertions Precondition { } when disabled       Then { result != Failure() }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/assertions_spec.rb:50
  Given::Assertions Postcondition { } with true assertion       Then { result != Failure() }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/assertions_spec.rb:59
  Given::Assertions Postcondition { } with false assertion       Then { result == Failure(Given::Assertions::PostconditionError, /Postcondition.*false/) }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/assertions_spec.rb:66
  Given::Assertions Postcondition { } when disabled       Then { result != Failure() }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/assertions_spec.rb:72
  Numeric Extensions   Then { n.±(0.001).exactly_equals?(delta_n) }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/ext/numeric_spec.rb:15
  Numeric Extensions   Then { n.‰(5).exactly_equals?(percent_n) }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/ext/numeric_spec.rb:16
  Numeric Extensions   Then { n.€(20).exactly_equals?(epsilon_n) }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/ext/numeric_spec.rb:17
  Numeric Extensions   Then { n.±.exactly_equals?(about_n) }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/ext/numeric_spec.rb:19
  Numeric Extensions   Then { n.‰.exactly_equals?(about_n) }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/ext/numeric_spec.rb:20
  Numeric Extensions   Then { n.€.exactly_equals?(about_n) }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/ext/numeric_spec.rb:21
  Given::FailureMatcher with matching failure results       Then { Failure(CustomError, "CUSTOM").matches?(failure_result) }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/failure_matcher_spec.rb:18
  Given::FailureMatcher with matching failure results       Then { Failure(CustomError, /CUSTOM/).matches?(failure_result) }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/failure_matcher_spec.rb:19
  Given::FailureMatcher with matching failure results       Then { Failure(CustomError).matches?(failure_result) }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/failure_matcher_spec.rb:20
  Given::FailureMatcher with matching failure results       Then { Failure(StandardError).matches?(failure_result) }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/failure_matcher_spec.rb:21
  Given::FailureMatcher with matching failure results       Then { Failure().matches?(failure_result) }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/failure_matcher_spec.rb:22
  Given::FailureMatcher with non-matching results       Then {
        expect {
          Failure(StandardError).matches?(Object.new)
        }.to raise_error(NotMetError,
          /Expected.*StandardError, but nothing failed/)
      }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/failure_matcher_spec.rb:26
  Given::FailureMatcher with non-matching results       Then {
        expect {
          Failure(StandardError, /CUSTOM/).matches?(Object.new)
        }.to raise_error(NotMetError,
          /Expected.*StandardError.*matching.*CUSTOM.*, but nothing failed/)
      }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/failure_matcher_spec.rb:33
  Given::FailureMatcher with non-matching results       Then {
        expect {
          Failure(StandardError, /OTHER/).matches?(failure_result)
        }.to raise_error(NotMetError,
          /Expected.*StandardError matching.*OTHER.*, but got.*CustomError.*CUSTOM/)
      }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/failure_matcher_spec.rb:40
  Given::FailureMatcher with non-matching results       Then {
        expect {
          Failure(OtherError, /CUSTOM/).matches?(failure_result)
        }.to raise_error(NotMetError,
          /Expected.*OtherError matching.*CUSTOM.*, but got.*CustomError.*CUSTOM/)
      }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/failure_matcher_spec.rb:47
  Given::FailureMatcher with non-matching results       Then {
        expect {
          Failure(SubError, /CUSTOM/).matches?(failure_result)
        }.to raise_error(NotMetError,
          /Expected.*SubError matching.*CUSTOM.*, but got.*CustomError.*CUSTOM/)
      }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/failure_matcher_spec.rb:54
  Given::FailureMatcher with non-matching results       Then {
        expect {
          Failure(OtherError).matches?(failure_result)
        }.to raise_error(NotMetError,
          /Expected.*OtherError, but got.*CustomError.*CUSTOM/)
      }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/failure_matcher_spec.rb:61
  Given::FailureMatcher ==       Then { failure_result       == Failure() }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/failure_matcher_spec.rb:70
  Given::FailureMatcher ==       Then { failure_result       == Failure(CustomError) }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/failure_matcher_spec.rb:71
  Given::FailureMatcher ==       Then { Failure()            == failure_result }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/failure_matcher_spec.rb:72
  Given::FailureMatcher ==       Then { Failure(CustomError) == failure_result }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/failure_matcher_spec.rb:73
  Given::FailureMatcher !=       Then { failure_result != Failure(SubError) }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/failure_matcher_spec.rb:77
  Given::FailureMatcher !=       Then { Failure(SubError) != failure_result }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/failure_matcher_spec.rb:78
  Given::FailureMatcher !=       Then { Failure() != nil }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/failure_matcher_spec.rb:79
  Given::FailureMatcher !=       Then { nil != Failure() }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/failure_matcher_spec.rb:80
  Given::Failure == have_failed     Then { failure == have_failed(StandardError, "Oops") }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/failure_spec.rb:31
  Given::Failure == have_failed     Then { failure == have_failed(StandardError) }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/failure_spec.rb:32
  Given::Failure == have_failed     Then { failure == have_failed }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/failure_spec.rb:33
  Given::Failure == Failure     Then { failure == Failure(StandardError, "Oops") }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/failure_spec.rb:38
  Given::Failure == Failure     Then { failure == Failure(StandardError) }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/failure_spec.rb:39
  Given::Failure == Failure     Then { failure == Failure() }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/failure_spec.rb:40
  Given::Failure != Failure     Then { expect { failure != Object.new }.to raise_error(StandardError) }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/failure_spec.rb:45
  Given::Failure != Failure     Then { failure != Failure(other_error) }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/failure_spec.rb:46
  Given::Fuzzy::FuzzyNumber attributes     Then { number.exact_value == 10 }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/fuzzy_number_spec.rb:9
  Given::Fuzzy::FuzzyNumber attributes     Then { number.delta_amount == 0.0001 }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/fuzzy_number_spec.rb:10
  Given::Fuzzy::FuzzyNumber attributes     Then { number.low_limit == (10 - 0.0001) }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/fuzzy_number_spec.rb:11
  Given::Fuzzy::FuzzyNumber attributes     Then { number.high_limit == (10 + 0.0001) }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/fuzzy_number_spec.rb:12
  Given::Fuzzy::FuzzyNumber#exactly_equals?     Then { number.exactly_equals?(number) }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/fuzzy_number_spec.rb:21
  Given::Fuzzy::FuzzyNumber#exactly_equals?     Then { number.exactly_equals?(same_number) }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/fuzzy_number_spec.rb:22
  Given::Fuzzy::FuzzyNumber#exactly_equals?     Then { ! number.exactly_equals?(different_exact) }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/fuzzy_number_spec.rb:24
  Given::Fuzzy::FuzzyNumber#exactly_equals?     Then { ! number.exactly_equals?(different_delta) }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/fuzzy_number_spec.rb:25
  Given::Fuzzy::FuzzyNumber fixed deltas     Then { exact_number == number }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/fuzzy_number_spec.rb:32
  Given::Fuzzy::FuzzyNumber fixed deltas     Then { (exact_number + 0.001) == number }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/fuzzy_number_spec.rb:34
  Given::Fuzzy::FuzzyNumber fixed deltas     Then { (exact_number - 0.001) == number }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/fuzzy_number_spec.rb:35
  Given::Fuzzy::FuzzyNumber fixed deltas     Then { (exact_number + 0.001001) != number }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/fuzzy_number_spec.rb:37
  Given::Fuzzy::FuzzyNumber fixed deltas     Then { (exact_number - 0.001001) != number }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/fuzzy_number_spec.rb:38
  Given::Fuzzy::FuzzyNumber negative deltas     Then { exact_number == number }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/fuzzy_number_spec.rb:45
  Given::Fuzzy::FuzzyNumber negative deltas     Then { (exact_number + 0.001) == number }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/fuzzy_number_spec.rb:47
  Given::Fuzzy::FuzzyNumber negative deltas     Then { (exact_number - 0.001) == number }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/fuzzy_number_spec.rb:48
  Given::Fuzzy::FuzzyNumber negative deltas     Then { (exact_number + 0.001001) != number }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/fuzzy_number_spec.rb:50
  Given::Fuzzy::FuzzyNumber negative deltas     Then { (exact_number - 0.001001) != number }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/fuzzy_number_spec.rb:51
  Given::Fuzzy::FuzzyNumber percentage deltas     Then { exact_number == number }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/fuzzy_number_spec.rb:58
  Given::Fuzzy::FuzzyNumber percentage deltas     Then { (exact_number + 0.25) == number }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/fuzzy_number_spec.rb:60
  Given::Fuzzy::FuzzyNumber percentage deltas     Then { (exact_number - 0.25) == number }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/fuzzy_number_spec.rb:61
  Given::Fuzzy::FuzzyNumber percentage deltas     Then { (exact_number + 0.25001) != number }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/fuzzy_number_spec.rb:63
  Given::Fuzzy::FuzzyNumber percentage deltas     Then { (exact_number - 0.25001) != number }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/fuzzy_number_spec.rb:64
  Given::Fuzzy::FuzzyNumber epsilon deltas when created with default delta when 1         Then { exact_number == number }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/fuzzy_number_spec.rb:85
  Given::Fuzzy::FuzzyNumber epsilon deltas when created with default delta when rather large         Then { exact_number == number }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/fuzzy_number_spec.rb:90
  Given::Fuzzy::FuzzyNumber epsilon deltas when created with default delta when rather small         Then { exact_number == number }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/fuzzy_number_spec.rb:95
  Given::Fuzzy::FuzzyNumber epsilon deltas when created with small epsilon       Then { exact_number == number }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/fuzzy_number_spec.rb:103
  Given::Fuzzy::FuzzyNumber#to_s     Then { number.to_s == "<Approximately 10 +/- 0.0001>" }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/fuzzy_number_spec.rb:109
  #have_failed with a pending exception       Then { Given.fail_with "This example should have been pending" }
    # Required pending in example ... please ignore
    # ./spec/lib/given/have_failed_spec.rb:47
  #have_failed with natural assertions with failure         Then { result == have_failed(CustomError, "Ouch") }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/have_failed_spec.rb:61
  #have_failed with natural assertions with failure         Then { ! (result != have_failed) }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/have_failed_spec.rb:62
  #have_failed with natural assertions with failure         Then { expect { result == :something }.to raise_error(CustomError, "Ouch") }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/have_failed_spec.rb:63
  #have_failed with natural assertions with different failure         Then { ! (result == have_failed(CustomError, "Ouch")) }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/have_failed_spec.rb:68
  Lexical Purity nested     Then { A == 1 }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/lexical_purity_spec.rb:13
  Lexical Purity nested     Then { avalue == 1 }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/lexical_purity_spec.rb:14
  Lexical Purity nested     Then { B == 2 }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/lexical_purity_spec.rb:15
  Lexical Purity nested     Then { bvalue == 2 }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/lexical_purity_spec.rb:16
  Lexical Purity nested     Then { LEXICAL_PURITY_GLOBAL_CONSTANT == 3 }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/lexical_purity_spec.rb:17
  Given::NaturalAssertion#content? with empty block       Then { expect(na).to_not have_content }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:12
  Given::NaturalAssertion#content? with block returning false       Then { expect(na).to have_content }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:16
  Given::NaturalAssertion passing criteria with true       Then { _gvn_block_passed?(faux_block) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:23
  Given::NaturalAssertion passing criteria with false       Then { ! _gvn_block_passed?(faux_block) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:28
  Given::NaturalAssertion passing criteria with to_bool/true       Then { _gvn_block_passed?(faux_block) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:34
  Given::NaturalAssertion passing criteria with to_bool/false       Then { ! _gvn_block_passed?(faux_block) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:40
  Given::NaturalAssertion failure messages with equals assertion       Then { expect(msg).to match(/\bexpected: +1\b/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:51
  Given::NaturalAssertion failure messages with equals assertion       Then { expect(msg).to match(/\bto equal: +2\b/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:52
  Given::NaturalAssertion failure messages with equals assertion       Then { expect(msg).to match(/\bfalse +<- +a == 2\b/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:53
  Given::NaturalAssertion failure messages with equals assertion       Then { expect(msg).to match(/\b1 +<- +a\b/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:54
  Given::NaturalAssertion failure messages with equals assertion with do/end       Then { expect(msg).to match(/\bexpected: +1\b/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:60
  Given::NaturalAssertion failure messages with equals assertion with do/end       Then { expect(msg).to match(/\bto equal: +2\b/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:61
  Given::NaturalAssertion failure messages with equals assertion with do/end       Then { expect(msg).to match(/\bfalse +<- +a == 2\b/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:62
  Given::NaturalAssertion failure messages with equals assertion with do/end       Then { expect(msg).to match(/\b1 +<- +a\b/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:63
  Given::NaturalAssertion failure messages with not-equals assertion       Then { expect(msg).to match(/\bexpected: +1\b/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:69
  Given::NaturalAssertion failure messages with not-equals assertion       Then { expect(msg).to match(/\bto not equal: +1\b/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:70
  Given::NaturalAssertion failure messages with not-equals assertion       Then { expect(msg).to match(/\bfalse +<- +a != 1\b/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:71
  Given::NaturalAssertion failure messages with not-equals assertion       Then { expect(msg).to match(/\b1 +<- +a\b/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:72
  Given::NaturalAssertion failure messages with less than assertion       Then { expect(msg).to match(/\bexpected: +1\b/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:78
  Given::NaturalAssertion failure messages with less than assertion       Then { expect(msg).to match(/\bto be less than: +1\b/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:79
  Given::NaturalAssertion failure messages with less than assertion       Then { expect(msg).to match(/\bfalse +<- +a < 1\b/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:80
  Given::NaturalAssertion failure messages with less than assertion       Then { expect(msg).to match(/\b1 +<- +a\b/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:81
  Given::NaturalAssertion failure messages with less than or equal to assertion       Then { expect(msg).to match(/\bexpected: +1\b/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:87
  Given::NaturalAssertion failure messages with less than or equal to assertion       Then { expect(msg).to match(/\bto be less or equal to: +0\b/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:88
  Given::NaturalAssertion failure messages with less than or equal to assertion       Then { expect(msg).to match(/\bfalse +<- +a <= 0\b/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:89
  Given::NaturalAssertion failure messages with less than or equal to assertion       Then { expect(msg).to match(/\b1 +<- +a\b/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:90
  Given::NaturalAssertion failure messages with greater than assertion       Then { expect(msg).to match(/\bexpected: +1\b/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:96
  Given::NaturalAssertion failure messages with greater than assertion       Then { expect(msg).to match(/\bto be greater than: +1\b/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:97
  Given::NaturalAssertion failure messages with greater than assertion       Then { expect(msg).to match(/\bfalse +<- +a > 1\b/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:98
  Given::NaturalAssertion failure messages with greater than assertion       Then { expect(msg).to match(/\b1 +<- +a\b/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:99
  Given::NaturalAssertion failure messages with greater than or equal to assertion       Then { expect(msg).to match(/\bexpected: +1\b/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:105
  Given::NaturalAssertion failure messages with greater than or equal to assertion       Then { expect(msg).to match(/\bto be greater or equal to: +3\b/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:106
  Given::NaturalAssertion failure messages with greater than or equal to assertion       Then { expect(msg).to match(/\bfalse +<- +a >= 3\b/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:107
  Given::NaturalAssertion failure messages with greater than or equal to assertion       Then { expect(msg).to match(/\b1 +<- +a\b/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:108
  Given::NaturalAssertion failure messages with match assertion       Then { expect(msg).to match(/\bexpected: +"Hello"$/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:114
  Given::NaturalAssertion failure messages with match assertion       Then { expect(msg).to match(/\bto match: +\/HI\/$/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:115
  Given::NaturalAssertion failure messages with match assertion       Then { expect(msg).to match(/\bnil +<- +s =~ \/HI\/$/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:116
  Given::NaturalAssertion failure messages with match assertion       Then { expect(msg).to match(/"Hello" +<- +s$/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:117
  Given::NaturalAssertion failure messages with not match assertion       Then { expect(msg).to match(/\bexpected: +"Hello"$/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:123
  Given::NaturalAssertion failure messages with not match assertion       Then { expect(msg).to match(/\bto not match: +\/Hello\/$/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:124
  Given::NaturalAssertion failure messages with not match assertion       Then { expect(msg).to match(/\bfalse +<- +s !~ \/Hello\/$/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:125
  Given::NaturalAssertion failure messages with not match assertion       Then { expect(msg).to match(/"Hello" +<- +s$/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:126
  Given::NaturalAssertion failure messages with exception       Then { expect(msg).to match(/\bexpected: +NoMethodError/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:132
  Given::NaturalAssertion failure messages with exception       Then { expect(msg).to match(/\bto equal: +3$/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:133
  Given::NaturalAssertion failure messages with exception       Then { expect(msg).to match(/\bNoMethodError.+NilClass\n +<- +ary\[1\] == 3$/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:134
  Given::NaturalAssertion failure messages with exception       Then { expect(msg).to match(/\bNoMethodError.+NilClass\n +<- +ary\[1\]$/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:135
  Given::NaturalAssertion failure messages with exception       Then { expect(msg).to match(/\bnil +<- +ary$/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:136
  Given::NaturalAssertion failure messages with value with newlines       Then { expect(msg).to match(/\n  false   <- zzzz\.ok\?/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:150
  Given::NaturalAssertion failure messages with value with newlines       Then { expect(msg).to match(/\n  XXXX\n/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:151
  Given::NaturalAssertion failure messages with value with newlines       Then { expect(msg).to match(/\n  YYYY\n/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:152
  Given::NaturalAssertion failure messages with value with newlines       Then { expect(msg).to match(/\n          <- zzzz$/) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:153
  Given::NaturalAssertion bad Then blocks with no statements       Then { expect(result).to_not have_failed }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:161
  Given::NaturalAssertion bad Then blocks with multiple statements       Then { expect(result).to have_failed(Given::InvalidThenError, /multiple.*statements/i) }
    # Natural Assertions disabled for JRuby
    # ./spec/lib/given/natural_assertion_spec.rb:170
  Configuration Options Global natural assertion configuration with no explicit word on natural assertions       Then { expect(_gvn_need_na_message?(nassert)).to be_falsy }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/options_spec.rb:46
  Configuration Options Global natural assertion configuration with no explicit word on natural assertions overridden locally         Then { expect(_gvn_need_na_message?(nassert)).to be_truthy }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/options_spec.rb:50
  Configuration Options Global natural assertion configuration with global configuration enabled       Then { expect(_gvn_need_na_message?(nassert)).to be_truthy }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/options_spec.rb:56
  Configuration Options Global natural assertion configuration with global configuration enabled overridden locally         Then { expect(_gvn_need_na_message?(nassert)).to be_falsy }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/options_spec.rb:60
  Configuration Options Global natural assertion configuration with global configuration enabled with rspec assertion         Then {
          if RSpec::Given::MONKEY
            # If RSpec was successfully patched to record matchers,
            # then the "need NA" logic will ignore possible matches in
            # the source code.
            expect(_gvn_need_na_message?(nassert)).to be_truthy
          else
            # If RSpec was not successfully patched to record
            # matchers, then the "need NA" logic will check for
            # should/expect in the source.
            expect(_gvn_need_na_message?(nassert)).to be_falsy
          end
        }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/options_spec.rb:65
  Configuration Options Global natural assertion configuration with global configuration enabled without rspec assertion         Then { expect(_gvn_need_na_message?(nassert)).to be_truthy }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/options_spec.rb:82
  Configuration Options Global natural assertion configuration with global configuration enabled without rspec assertion and no content         Then { expect(_gvn_need_na_message?(nassert)).to be_falsy }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/options_spec.rb:88
  Configuration Options Global natural assertion configuration with global configuration set to always       Then { expect(_gvn_need_na_message?(nassert)).to be_truthy }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/options_spec.rb:94
  Configuration Options Global natural assertion configuration with global configuration set to always overridden locally         Then { expect(_gvn_need_na_message?(nassert)).to be_falsy }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/options_spec.rb:98
  Configuration Options Global natural assertion configuration with global configuration set to always with rspec assertion         Then { expect(_gvn_need_na_message?(nassert)).to be_truthy }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/options_spec.rb:103
  Configuration Options Global natural assertion configuration with global configuration set to always without rspec assertion         Then { expect(_gvn_need_na_message?(nassert)).to be_truthy }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/options_spec.rb:108
  Configuration Options Global natural assertion configuration with global configuration set to always without rspec assertion and no content         Then { expect(_gvn_need_na_message?(nassert)).to be_falsy }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/options_spec.rb:114
  Configuration Options Global natural assertion configuration with global configuration disabled       Then { expect(_gvn_need_na_message?(nassert)).to be_falsy }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/options_spec.rb:120
  Configuration Options Global natural assertion configuration with global configuration disabled overridden locally         Then { expect(_gvn_need_na_message?(nassert)).to be_truthy }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/options_spec.rb:124
  Configuration Options Global natural assertion configuration with global configuration disabled with rspec assertion         Then { expect(_gvn_need_na_message?(nassert)).to be_falsy }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/options_spec.rb:129
  Configuration Options Global natural assertion configuration with global configuration disabled without rspec assertion         Then { expect(_gvn_need_na_message?(nassert)).to be_falsy }
    # Natural assertions are not supported in JRuby
    # ./spec/lib/given/options_spec.rb:134

Failures:

  1) Failing Then clauses with false     FAIL { false }
     Failure/Error: FAIL { false }
       expected RSpec::Expectations::ExpectationNotMetError but nothing was raised
     # ./spec/support/failure_and_errors.rb:10:in `_gvn_fail'
     # ./spec/lib/given/failing_thens_spec.rb:10:in `Then'

Finished in 0.399 seconds
251 examples, 1 failure, 149 pending

Failed examples:

rspec ./spec/lib/given/failing_thens_spec.rb:10 # Failing Then clauses with false     FAIL { false }
rake aborted!
Command failed with status (1): [rspec spec...]
/Users/justin/code/rspec-given/rspec-given/Rakefile:59:in `(root)'
Tasks: TOP => default => examples => specs
(See full trace by running task with --trace)
```

**Comment by searls** [comment]
Since I'm not a regular jruby user, I'd encourage anyone who has a better understanding of the jruby project to take a stab at this one.

**Comment by jkowens** [comment]
@searls This turned out to be a simple fix. Jim's method of determining if the JRuby in use supported natural assertions didn't work for versions > 1.7.9. Hope you don't mind me sending up a pull request.

**Comment by searls** [comment]
Please do
