### ISSUE TITLE
specs are not running using truffle ruby

### ISSUE THREAD

**Issue by topofocus** [rspec-given/rspec-given#29]
Hi folks,
I am experimenting with truffleruby (GraalVM). 
They claim to be compatible with ruby 2.6.2. 

When executing specs, this error approaches

```
An error occurred while loading ./spec/lib/model_spec.rb.
Failure/Error: Then { expect(first_document ).to be_a ActiveOrient::Model }

Errno::ENOENT:
  No such file or directory - (eval)
# ./spec/lib/model_spec.rb:110:in `block (3 levels) in <top (required)>'
# ./spec/lib/model_spec.rb:108:in `block (2 levels) in <top (required)>'
# ./spec/lib/model_spec.rb:85:in `block in <top (required)>'
# ./spec/lib/model_spec.rb:14:in `<top (required)>'
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Finished in 0.013 seconds (files took 12.99 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```
The error vanishes, if I remove Given/Then. 

Thus its the rspec-gem raising the ENOENT Error. 
Most likely, a blank is missing between '-' and an expression.
Seems that the truffle-ruby implementation has difficulties to distinguish between binary and unary operators. 

Can anybody familiar with the gem give a hint, where to look to to fix this?

**Comment by searls** [comment]
Since we haven't pushed out a release in, like, forever, try pulling down the repo and upgrading to a newer version of sorcerer. That might fix you

**Comment by searls** [comment]
Any update? Since I don't have any experience with TruffleRuby I think I'll need more help debugging (and potentially patching) any underlying issue here.

**Comment by topofocus** [comment]
Will investigate after the holidays (in germany, we celibrate "Vatertag")

**Comment by topofocus** [comment]
Even using the master branch, specs are not running at all. 

output of bundle update  and rspec spec/lib/hash_spec.rb
```
Using guard 2.15.0
Using guard-compat 1.2.1
Using rspec-support 3.8.0
Using rspec-core 3.8.0
Using rspec-expectations 3.8.3
Using rspec-mocks 3.8.0
Using rspec 3.8.0
Using guard-rspec 4.7.3
Using rdoc 6.1.1
Using rspec-collection_matchers 1.1.3
Using rspec-context-private 0.0.1
Using rspec-given 3.8.0 from source at `../rspec-given`
Using rspec-its 1.3.0
Using rspec-legacy_formatters 1.0.1
Using sdoc 1.0.0
Bundle updated!
ubuntu@graal:~/active-orient$ rspec spec/lib/hash_spec.rb 

An error occurred while loading ./spec/lib/hash_spec.rb.
Failure/Error: Then {record.ll.is_a? Hash }

Errno::ENOENT:
  No such file or directory - (eval)
# /home/ubuntu/rspec-given/lib/given/file_cache.rb:15:in `internal_raise'
# /home/ubuntu/rspec-given/lib/given/file_cache.rb:15:in `raise'
# /home/ubuntu/rspec-given/lib/given/file_cache.rb:15:in `handle'
# /home/ubuntu/rspec-given/lib/given/file_cache.rb:15:in `sysopen'
# /home/ubuntu/rspec-given/lib/given/file_cache.rb:15:in `initialize'
# /home/ubuntu/rspec-given/lib/given/file_cache.rb:15:in `new'
# /home/ubuntu/rspec-given/lib/given/file_cache.rb:15:in `open'
# /home/ubuntu/rspec-given/lib/given/file_cache.rb:15:in `open'
# /home/ubuntu/rspec-given/lib/given/file_cache.rb:15:in `read_lines'
# /home/ubuntu/rspec-given/lib/given/file_cache.rb:9:in `get'
# /home/ubuntu/rspec-given/lib/given/line_extractor.rb:11:in `line'
# /home/ubuntu/rspec-given/lib/given/extensions.rb:255:in `Then'
# ./spec/lib/hash_spec.rb:30:in `block (2 levels) in <top (required)>'
# ./spec/lib/hash_spec.rb:27:in `block in <top (required)>'
# ./spec/lib/hash_spec.rb:6:in `<top (required)>'
```
row 6  requires rspec/given ....
