### ISSUE TITLE
fix the build

### ISSUE THREAD

**Issue by searls** [rspec-given/rspec-given#9]
The build broke by happenstance 4 months ago and it's not clear why (perhaps a dependency got ahead of us or a ruby version change)
## Here's it passing on my local machine (with an old install):

```
$ be rake
Running specs
rspec spec
............................................................................................................................................................*...............................................................................................

Pending:
  #have_failed with a pending invocation       Then { Given.fail_with "This example should have been regarded as pending" }

    # Forcing a pending in example ... please ignore
    # ./spec/lib/given/have_failed_spec.rb:54

Finished in 0.12863 seconds (files took 0.33309 seconds to load)
252 examples, 0 failures, 1 pending
Running examples (with RSpec2)
rspec examples/integration/and_spec.rb examples/integration/failing_messages_spec.rb examples/integration/focused_line_spec.rb examples/integration/given_spec.rb examples/integration/invariant_spec.rb examples/integration/then_spec.rb examples/stack/stack_spec.rb examples/use_assertions.rb
......................................

Finished in 2.1 seconds (files took 0.08821 seconds to load)
38 examples, 0 failures
Running examples (with Minitest)
ruby -Ilib:examples examples/loader.rb examples/integration/and_spec.rb examples/integration/failing_messages_spec.rb examples/integration/focused_line_spec.rb examples/integration/given_spec.rb examples/integration/invariant_spec.rb examples/integration/then_spec.rb examples/stack/stack_spec.rb examples/use_assertions.rb examples/minitest/assert_raises_spec.rb
Run options: --seed 44784

# Running:

............................................

Finished in 2.186130s, 20.1269 runs/s, 39.3389 assertions/s.

44 runs, 86 assertions, 0 failures, 0 errors, 0 skips
```

The passing install has:

```
$ ruby -v
ruby 2.1.1p76
$ bundle -v
Bundler version 1.7.4
$ cat Gemfile.lock 
GEM
  remote: https://rubygems.org/
  specs:
    diff-lcs (1.2.5)
    minitest (5.5.0)
    rake (10.4.2)
    rspec (3.1.0)
      rspec-core (~> 3.1.0)
      rspec-expectations (~> 3.1.0)
      rspec-mocks (~> 3.1.0)
    rspec-core (3.1.7)
      rspec-support (~> 3.1.0)
    rspec-expectations (3.1.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.1.0)
    rspec-mocks (3.1.3)
      rspec-support (~> 3.1.0)
    rspec-support (3.1.2)
    sorcerer (1.0.2)

PLATFORMS
  java
  ruby

DEPENDENCIES
  minitest (>= 4.3)
  rake
  rspec (>= 2.14.0)
  sorcerer (>= 0.3.7)
```
## Meanwhile, on another machine it's failing (newer install):

```
$ be rake
Running specs
rspec spec
..................................................................................................WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call. Instead consider providing a specific error class or message. This message can be supressed by setting: `RSpec::Expectations.configuration.warn_about_potential_false_positives = false`. Called from /Users/justin/code/rspec-given/rspec-given/lib/given/rspec/monkey.rb:21:in `handle_matcher'.
...................................................WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call. Instead consider providing a specific error class or message. This message can be supressed by setting: `RSpec::Expectations.configuration.warn_about_potential_false_positives = false`. Called from /Users/justin/code/rspec-given/rspec-given/lib/given/rspec/monkey.rb:21:in `handle_matcher'.
.......*...............................................................................................

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) #have_failed with a pending invocation       Then { Given.fail_with "This example should have been regarded as pending" }

     # Forcing a pending in example ... please ignore
     Failure/Error: Then { Given.fail_with "This example should have been regarded as pending" }
       This example should have been regarded as pending
     # ./lib/given/rspec/framework.rb:24:in `fail_with'
     # ./lib/given/module_methods.rb:59:in `fail_with'
     # ./spec/lib/given/have_failed_spec.rb:54:in `block (3 levels) in <module:HaveFailedSpec>'
     # ./lib/given/extensions.rb:108:in `instance_eval'
     # ./lib/given/extensions.rb:108:in `_gvn_block_passed?'
     # ./lib/given/extensions.rb:116:in `_gvn_evaluate'
     # ./lib/given/extensions.rb:102:in `_gvn_then'
     # ./spec/lib/given/have_failed_spec.rb:54:in `block in Then'

Finished in 0.22848 seconds (files took 0.39778 seconds to load)
252 examples, 0 failures, 1 pending

Running examples (with RSpec2)
rspec examples/integration/and_spec.rb examples/integration/failing_messages_spec.rb examples/integration/focused_line_spec.rb examples/integration/given_spec.rb examples/integration/invariant_spec.rb examples/integration/then_spec.rb examples/stack/stack_spec.rb examples/use_assertions.rb
.......F..............................

Failures:

  1) Failing Messages when referencing undefined methods     Then { ios.err == "" }

     Failure/Error: Then { ios.err == "" }
       And expression failed at /Users/justin/code/rspec-given/rspec-given/examples/integration/failing_messages_spec.rb:25
       Failing expression: And { ios.out =~ /undefined local variable or method `xyz'/ }
       expected: "F\n\nFailures:\n\n  1) Then with nesting   Then { xyz }\n\n     Failure/Error: Then { xyz }\n       `xyz` is not available from within an example (e.g. an `it` block) or from constructs that run in the scope of an example (e.g. `before`, `let`, etc). It is only available on an example group (e.g. a `describe` or `context` block).\n     # ./examples/integration/failing/undefined_method_spec.rb:8:in `block (2 levels) in <top (required)>'\n     # ./lib/given/extensions.rb:108:in `instance_eval'\n     # ./lib/given/extensions.rb:108:in `_gvn_block_passed?'\n     # ./lib/given/extensions.rb:116:in `_gvn_evaluate'\n     # ./lib/given/extensions.rb:102:in `_gvn_then'\n     # ./examples/integration/failing/undefined_method_spec.rb:8:in `block in Then'\n\nFinished in 0.00059 seconds (files took 0.16553 seconds to load)\n1 example, 1 failure\n\nFailed examples:\n\nrspec ./examples/integration/failing/undefined_method_spec.rb:8 # Then with nesting   Then { xyz }\n\n\n"
       to match: /undefined local variable or method `xyz'/
         nil   <- ios.out =~ /undefined local variable or method `xyz'/
         "F\n\nFailures:\n\n  1) Then with nesting   Then { xyz }\n\n     Failure/Error: Then { xyz }\n       `xyz` is not available from within an example (e.g. an `it` block) or from constructs that run in the scope of an example (e.g. `before`, `let`, etc). It is only available on an example group (e.g. a `describe` or `context` block).\n     # ./examples/integration/failing/undefined_method_spec.rb:8:in `block (2 levels) in <top (required)>'\n     # ./lib/given/extensions.rb:108:in `instance_eval'\n     # ./lib/given/extensions.rb:108:in `_gvn_block_passed?'\n     # ./lib/given/extensions.rb:116:in `_gvn_evaluate'\n     # ./lib/given/extensions.rb:102:in `_gvn_then'\n     # ./examples/integration/failing/undefined_method_spec.rb:8:in `block in Then'\n\nFinished in 0.00059 seconds (files took 0.16553 seconds to load)\n1 example, 1 failure\n\nFailed examples:\n\nrspec ./examples/integration/failing/undefined_method_spec.rb:8 # Then with nesting   Then { xyz }\n\n\n"
               <- ios.out
         #<struct IOS out="F\n\nFailures:\n\n  1) Then with nesting   Then { xyz }\n\n     Failure/Error: Then { xyz }\n       `xyz` is not available from within an example (e.g. an `it` block) or from constructs that run in the scope of an example (e.g. `before`, `let`, etc). It is only available on an example group (e.g. a `describe` or `context` block).\n     # ./examples/integration/failing/undefined_method_spec.rb:8:in `block (2 levels) in <top (required)>'\n     # ./lib/given/extensions.rb:108:in `instance_eval'\n     # ./lib/given/extensions.rb:108:in `_gvn_block_passed?'\n     # ./lib/given/extensions.rb:116:in `_gvn_evaluate'\n     # ./lib/given/extensions.rb:102:in `_gvn_then'\n     # ./examples/integration/failing/undefined_method_spec.rb:8:in `block in Then'\n\nFinished in 0.00059 seconds (files took 0.16553 seconds to load)\n1 example, 1 failure\n\nFailed examples:\n\nrspec ./examples/integration/failing/undefined_method_spec.rb:8 # Then with nesting   Then { xyz }\n\n\n", err="">
               <- ios
     # ./lib/given/rspec/framework.rb:24:in `fail_with'
     # ./lib/given/module_methods.rb:59:in `fail_with'
     # ./lib/given/extensions.rb:127:in `_gvn_naturally_assert'
     # ./lib/given/extensions.rb:118:in `_gvn_evaluate'
     # ./lib/given/extensions.rb:93:in `block in _gvn_check_ands'
     # ./lib/given/extensions.rb:92:in `each'
     # ./lib/given/extensions.rb:92:in `_gvn_check_ands'
     # ./lib/given/extensions.rb:103:in `_gvn_then'
     # ./examples/integration/failing_messages_spec.rb:24:in `block in Then'

Finished in 4.2 seconds (files took 0.21459 seconds to load)
38 examples, 1 failure

Failed examples:

rspec ./examples/integration/failing_messages_spec.rb:24 # Failing Messages when referencing undefined methods     Then { ios.err == "" }


rake aborted!
Command failed with status (1): [rspec examples/integration/and_spec.rb exa...]
/Users/justin/code/rspec-given/rspec-given/Rakefile:84:in `block in <top (required)>'
Tasks: TOP => default => examples => rs_examples
(See full trace by running task with --trace)
```

The failing machine has:

```
$ ruby -v
ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-darwin14.0]

$ bundle -v
Bundler version 1.9.4

$ cat Gemfile.lock 
GEM
  remote: https://rubygems.org/
  specs:
    diff-lcs (1.2.5)
    minitest (5.7.0)
    rake (10.4.2)
    rspec (3.3.0)
      rspec-core (~> 3.3.0)
      rspec-expectations (~> 3.3.0)
      rspec-mocks (~> 3.3.0)
    rspec-core (3.3.1)
      rspec-support (~> 3.3.0)
    rspec-expectations (3.3.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.3.0)
    rspec-mocks (3.3.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.3.0)
    rspec-support (3.3.0)
    sorcerer (1.0.2)

PLATFORMS
  ruby

DEPENDENCIES
  minitest (>= 4.3)
  rake
  rspec (>= 2.14.0)
  sorcerer (>= 0.3.7)
```

**Comment by searls** [comment]
Looks like RSpec 3.2 or 3.3 added more informative language about the failure of class methods defined in example groups being unreachable from examples.

**Comment by searls** [comment]
Yup, here it is:

https://github.com/rspec/rspec-core/blob/aaf2964fe62c65adeedd27079a040a51a64b2bcd/lib/rspec/core/example_group.rb#L646-L654

Landed in 3.2

**Comment by searls** [comment]
^ Choosing to fix the above by simply changing the message in the expectation. This will cause the build to fail for versions of Rspec between 2 and 3.2, but since there are 0 dev machines who can't update, it should be fine (and better than adding a conditional to the test)

**Comment by searls** [comment]
There was an additional breakage caused by a new version of minitest, which actively errors out when someone tries to use let to override an existing method defined in minitest::spec (in this case, `value`). Updating the test fixed it
